### ISSUE TITLE
Singularity update

### ISSUE THREAD

**Issue by KevinSayers** [NREL/HPC#10]
Singularity page still references Peregrine. Also additional suggested changes:

- [ ] Add GPU section 
- [ ] Add a comparison of Docker / Singularity
- [x] Add recommendation of making Docker images which can be pulled as Singularity containers for portability
- [x] Check status of `singularity.automounts = True` for read/write in new version of Singularity on Eagle 
- [ ] Steps to create Singularity container from Docker daemon directly 
- [ ] Stub for NREL's Harbor registry.

**Comment by diskwarrior** [comment]
Closing. Most is covered in current (updated) docs. Creating individual issues for blog posts.
