### ISSUE TITLE
New MSS info in gh-pages

### ISSUE THREAD

**Issue by diskwarrior** [NREL/HPC#110]
Transfer this CMS content to mss.md and update with current info: https://www.nrel.gov/hpc/mass-storage-system.html

The policy page (https://www.nrel.gov/hpc/mass-storage-system-policies.html)  will stay on the CMS.

**Comment by yandthj** [comment]
MSS page should include any content about how to use MSS. Overview will be on the CMS
https://www.nrel.gov/hpc/mass-storage-system.html
