### ISSUE TITLE
FastX docs 

### ISSUE THREAD

**Issue by KevinSayers** [NREL/HPC#125]
Add how to reattach to a FastX session to the docs.

**Comment by KevinSayers** [comment]
Currently no FastX docs in the gh-pages. One issue that came up in a ticket was that users are leaving FastX sessions activ and not reattaching to them which slowly eats up availability. The suggestion is to document the process for reattaching, and perhaps also include other documentation for FastX in gh-pages.

**Comment by yandthj** [comment]
completed with PR #175
