### ISSUE TITLE
HPC/applications/plexos-quick-start/ internal link

### ISSUE THREAD

**Issue by jml5413** [NREL/HPC#16]
There's an internal link in HPC/applications/plexos-quick-start/ to confluence (https://tickets.hpc.nrel.gov/collab/display/CSCT/Eagle+Plexos+Examples). Can we post this somewhere so that both our internal and external users can access the content?

**Comment by k1nshuk** [comment]
@yandthj I created a PR https://github.com/NREL/HPC/pull/139 to avoid links pointing to internal NREL websites. I think I got all of them.

**Comment by yandthj** [comment]
#139
