### ISSUE TITLE
Add Module Page for Kestrel

### ISSUE THREAD

**Issue by diskwarrior** [NREL/HPC#168]
I noticed that the [conda](https://nrel.github.io/HPC/Documentation/Software_Tools/conda/) page just jumps into conda use and talks about modules midway through without much explanation. The building packages pages talks about modules you build and maintain, but it'd be nice to have a basic doc page on using modules. Then, link where appropriate (Swift and Vermilion have ml pages).

Maybe convert this: https://www.nrel.gov/hpc/eagle-environment-modules.html

**Comment by yandthj** [comment]
Superseded by #464
