### ISSUE TITLE
Updates needed to Vermilion documentation

### ISSUE THREAD

**Issue by claralarson** [NREL/HPC#179]
A user submitted a ticket after setting partition=test and pertition=debug on Vermilion (per the documentation at https://nrel.github.io/HPC/Documentation/Systems/Vermillion/running/. But these partitions do not exist. There are also a few paths referenced in the documentation that do not exist.

Things that need to be updated:
- change references to "test" or "debug" to "t", change "sm" to "std" (or "t"?)
- environment path doesn't exist: /nopt/nrel/apps/123456a/myenv.123456789
- path does not exist: /nopt/nrel/slurm/bin
- path does not exist: /nopt/nrel/apps/123456a/level01/gcc-9.4.0/slurm-20-11-5-1/lib/libpmi2.so
- can't load vasp via "ml vasp" because environment can't be loaded

How do we choose which environment to recommend to users?

**Comment by yandthj** [comment]
Add to the page info about the number of CPUs on nodes
in each partition.
CPUTot=4 Partitions=t
CPUTot=30 Partitions=std
CPUTot=16 Partitions=sm
CPUTot=60 Partitions=lg
CPUTot=30 Partitions=gpu

**Comment by yandthj** [comment]
Resolved with PR #186
