### ISSUE TITLE
How to transfer files needs updated

### ISSUE THREAD

**Issue by jml5413** [NREL/HPC#18]
HPC/general/beginner/how-to-transfer-files the readme needs updated from Peregrine and how to transfer files. Could use another markdown referencing something like FileZilla

**Comment by KevinSayers** [comment]
See #28 for draft of work. This is currently based on the gh-pages-dev branch not master. 

I am not too familiar with FileZilla or related tools. Would you up for writing up a doc?

**Comment by diskwarrior** [comment]
We should remove level specifications (beginner, intermediate) and flatten the structure...

**Comment by KevinSayers** [comment]
#28 Should have fixed this issue. Closing.
