### ISSUE TITLE
Migrate "Running Jobs" Content to Pages

### ISSUE THREAD

**Issue by tdthatcher** [NREL/HPC#208]
[https://www.nrel.gov/hpc/eagle-running-jobs.html](https://www.nrel.gov/hpc/eagle-running-jobs.html)

The content in these sub-categories of the eagle-running-jobs CMS page should be migrated over to Github Pages:

    [Partitions & Scheduling](https://www.nrel.gov/hpc/eagle-job-partitions-scheduling.html)
    [Job Priorities](https://www.nrel.gov/hpc/eagle-job-priorities.html)
    [Batch Jobs](https://www.nrel.gov/hpc/eagle-batch-jobs.html)
    [Interactive Jobs](https://www.nrel.gov/hpc/eagle-interactive-jobs.html)
    [Multiple Sub-Jobs](https://www.nrel.gov/hpc/eagle-multiple-sub-jobs.html)
    [Sample Batch Scripts](https://www.nrel.gov/hpc/eagle-sample-batch-script.html)
    [Debugging at Scale](https://www.nrel.gov/hpc/eagle-debugging-approaches.html)
    [Monitor & Control Commands](https://www.nrel.gov/hpc/eagle-monitor-control-commands.html)

The content on the CMS eagle-running-jobs frontpage should remain in place, but with an added link along the lines of "for detailed instructions and examples, visit the User Documentation site". The sub-categories can then be removed from the CMS site.

Considerations: should the info in these sections be generalized as it's ported over, with links to cluster-specific information (partition layouts, scheduling policies e.g. Fairshare, etc.)?

**Comment by tdthatcher** [comment]
Conversion to markdown and replacing references to Eagle with Kestrel is in progress. Converted pages will need further review and edit once more system-specific details are available.

**Comment by tdthatcher** [comment]
The revised section on Running Jobs should also probably include something like a "FAQ About Running Jobs" page with common questions from tickets. See also https://docs.nersc.gov/jobs/troubleshooting/ for inspiration. I'll include that as a part of this framework, additions or alterations can be made later.

**Comment by tdthatcher** [comment]
See [https://github.com/NREL/HPC/pull/221](https://github.com/NREL/HPC/pull/221) for first draft.

**Comment by yandthj** [comment]
Content migrated, captured improvement ideas in issue #423
