### ISSUE TITLE
Add "Paraview" section 

### ISSUE THREAD

**Issue by yandthj** [NREL/HPC#226]
In the "Applications" section, add a section for Paraview. Link to scripts in the code repo when appropriate. Migrate any content that is in the Github code repo that is verbose explanation.

The content that is in the CMS pages on Plexos should be migrated: 

https://www.nrel.gov/hpc/eagle-software-paraview.html

**Comment by yandthj** [comment]
See PR draft #232 for navigation structure and examples

**Comment by arswalid** [comment]
PR https://github.com/NREL/HPC/pull/253 submitted

**Comment by yandthj** [comment]
Complete with PR #321
