### ISSUE TITLE
Migrate relevant Announcements technical content to blog posts for April. and March 2022

### ISSUE THREAD

**Issue by yandthj** [NREL/HPC#234]

**Comment by tdthatcher** [comment]
March 2022: created new post for "Eagle local I/O performance", this is some useful information, and makes a great blog entry. I'll create a PR for it shortly.

April 2022: I could take the "CSC Tutorials Team - External Users", but this is also posted on the CMS blog as a separate entry, so I don't know that it's needed. I'll leave it out for now.

**Comment by tdthatcher** [comment]
https://github.com/NREL/HPC/pull/250 created.
