### ISSUE TITLE
References to Peregrine

### ISSUE THREAD

**Issue by jml5413** [NREL/HPC#26]
There are references to Peregrine in:

HPC/general/intermediate/building-packages/

and 

HPC/general/intermediate/software-environment-basics/conda-how-to.md

**Comment by chchang6** [comment]
Thanks for pointing this out, I've updated the building-packages example for OpenMPI on Eagle. Will assign our Conda person to update that example.

**Comment by chchang6** [comment]
Hey @KevinSayers , do you know if Harry has access to this repo? You could probably reproduce the Conda example as well; since the default Conda Python is version 3 now, maybe an example to create a version 2 installation would be more impressive.

**Comment by KevinSayers** [comment]
@chchang6 I am not sure if Harry has merge capabilities, I don't seem to have permissions to see the repo settings despite being able to merge. He has access to the repo though and can always fork/PR. 

The Conda docs could use some work as there are 2 versions (intermediate/software-environment-basics/ and languages/python/anaconda/) which could be consolidated. The GH pages currently only has the python one (https://nrel.github.io/HPC/languages/python/conda.html)

The Python 2 idea is interesting. Adding some info on Py 2->3 could be useful too?

**Comment by chchang6** [comment]
Yes re: Py 2 -> 3, I could use that right now as a matter of fact.
I can’t seem to assign anything to Harry. Dan/ACO owns the repo, is that right?

**Comment by diskwarrior** [comment]
I looked for Harry's github... wasn't sure he actively used harrysorensennrel (which I take is his?) Also, I bumped @KevinSayers to admin.

**Comment by chchang6** [comment]
@diskwarrior harrysorensennrel sounds right, but isn't coming up for me. I found pugswald, but doesn't look active.

**Comment by diskwarrior** [comment]
@harrysorensennrel, Anything to contribute here?

**Comment by harrysorensennrel** [comment]
I can update the example to install an older version of python if you think that's useful.  From experience, nearly all libraries that are used on the HPC have migrated to Python3.  Is there a library you have in mind that isn't available in Python3?

The application 2to3 exists in the default conda repo.  Did you want a link to the man page added or is there a use case you are envisioning that could use a detailed walkthrough?

**Comment by chchang6** [comment]
@harrysorensennrel @KevinSayers @diskwarrior Yeah Harry, you're probably right, and we should avoid encouraging Python 2 use if it can be avoided.

2to3 is useful in certain cases, though, particularly for academic offerings written in 2 that will never get ported to 3. 

Maybe the user story could be "I need to use an awful Python 2 module that will never be updated to Python 3, how can I do it?" and options (1--find an alternative so you can use up-to-date auxiliary tools; 2--convert to 3 so you can use up-to-date auxiliary tools, include link to https://docs.python.org/3/library/2to3.html; 3--set up a Python 2 custom environment).

**Comment by yandthj** [comment]
References to Peregrine in beginner md, fortran, how to use singularity...
