### ISSUE TITLE
Message says spark config was "created" but might not have been due to permissions

### ISSUE THREAD

**Issue by ahcyip** [NREL/HPC#603]
@daniel-thom 
![image](https://github.com/NREL/HPC/assets/5713411/9283a4ea-eb65-41bd-b832-928e4799eed3)

**Comment by daniel-thom** [comment]
I'll post a PR to fix this by tomorrow.

**Comment by yandthj** [comment]
@ahcyip Can you confirm if PR #605 fixes this issue?
