### ISSUE TITLE
Resources on migrating workflows from CPU to GPU 

### ISSUE THREAD

**Issue by yandthj** [NREL/HPC#632]
General conceptual considerations for migrating workflows from CPU to GPU
Some ideas from Matt:

- Is data/algorithm suited for GPU computation
- cost of copying data from CPU to GPU 
- tensorflow or pytorch example
- jit compilation with numba

**Comment by mselensky** [comment]
Adding notes for myself:

- Provide example Numba notebook for JIT compilation examples: element-wise (via @vectorize) and non-element-wise (via @cuda.jit)
- Provide conda recipe .yaml for users to reproduce this notebook (and/or containerize the notebook env depending on how complicated it gets)

**Comment by mselensky** [comment]
PR [here](https://github.com/NREL/HPC/pull/658)

**Comment by yandthj** [comment]
Complete with PR #658
