### ISSUE TITLE
Update the Containerized Tensorflow page for apptainer

### ISSUE THREAD

**Issue by jlaw9** [NREL/HPC#674]
The [Containerized TensorFlow](https://nrel.github.io/HPC/Documentation/Machine_Learning/Containerized_TensorFlow/) page needs to be updated for apptainer. 

Still very helpful though! I was able to build a TF image and run it successfully on kestrel using apptainer. I'm having a bit of trouble mounting/binding the input/output files to kestrel's file system though

**Comment by yandthj** [comment]
@jlaw9 Updates have been posted here: https://nrel.github.io/HPC/Documentation/Machine_Learning/Containerized_TensorFlow/

Let us know if you have any remaining questions/issues

**Comment by jlaw9** [comment]
Great thank you! I didn't realize you could just bind `/projects` directly. That should make things easier.

I'll try out the updated commands and let you know if I have any issues.
