### ISSUE TITLE
Recommendation for Anaconda

### ISSUE THREAD

**Issue by erskordi** [NREL/HPC#68]
The description of installing Anaconda environments given in (https://nrel.github.io/HPC/languages/python/conda.html is quite thorough. My only suggestion would be to add a small subsection for cloning an already existing environment. 

It can be used in case there is an existing environment somewhere on Eagle that works without issues and one wants to use it as a basis for their own environment. By cloning it, one can then add other packages as well and use it for their own projects. This is useful e.g. for cases when one wants to utilize GPUs for reinforcement learning policy training and do not want to create an environment from scratch, which can be proved to be cumbersome (CuDNN drivers, TF-gpu, etc.)

You can clone an environment as:
```
conda create --clone <env_name> --name <env_name_copy>
```

**Comment by diskwarrior** [comment]
Closed via #80
