### ISSUE TITLE
Jupyterhub

### ISSUE THREAD

**Issue by chchang6** [NREL/HPC#7]
Just starting the conversation to get JH docs up on website, and flesh out in repo.

First thing, have the admins seen this? https://github.com/jupyterhub/the-littlest-jupyterhub
I hadn't seen this before; since we already have an instance, this would only be interesting if it lowered management overhead dramatically or provided options more easily than the current instance. We're well within the 100-user limit.

Second, who is part of the "Jupyterhub" team now? We probably need >= 1 ACO person who can make changes to the instance, and 1 HPC Apps person in charge of usage/documentation.

**Comment by yandthj** [comment]
Jupyter added to pages: PR #183
