### ISSUE TITLE
Error installing tensorflow from wheel

### ISSUE THREAD

**Issue by erskordi** [NREL/HPC#79]
Hi,

I'm following the steps (https://github.com/NREL/HPC/tree/master/workshops/Optimized_TF) for creating an environment similar to py38tf24.yml but when I reach the point to install the precompiled TensorFlow installation from a wheel, I get the following error:

```
ERROR: tensorflow-2.4.0-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.
```

Any ideas?

**Comment by KevinSayers** [comment]
@erskordi hm odd, I just double checked and was able to install it in a clean environment. Just to clarify this is on an Eagle node you are getting this?

**Comment by erskordi** [comment]
Yes, I tried to install it on a `projects` subdirectory, maybe it works only on `home` directory? I also added few packages, because I want to try my RL stuff using the optimized TF-GPU

**Comment by KevinSayers** [comment]
I was able to install in a `/projects` env too. Could you try the below minimal setup and see if that works? 

Create just an empty Python env. 
```
conda create -n tftest python=3.8
```

Install just the wheel:
```
pip install --upgrade --no-deps --force-reinstall /nopt/nrel/apps/wheels/tensorflow-2.4.0-cp38-cp38-linux_x86_64.whl
```

**Comment by erskordi** [comment]
That worked, interesting

**Comment by KevinSayers** [comment]
Yea I believe that is because the `--no-deps` flag if you run without that it should install six and the other dependencies. Did you install TF first or your other packages? It would be an odd error to get from a dependency conflict.

**Comment by erskordi** [comment]
I didn't install any other packages, only followed your suggestion. The point is that tf installed successfuly though

**Comment by erskordi** [comment]
OK, so I rearranged the package order on the conda environment yaml file and instead of `source activate ...` I used `conda activate ...` and I didn't see the error this time. And actually I think it's a good idea to change the deprecated `source` with the `conda` option in the workshop, if you agree.

Since it works this way, perhaps we can close the issue. Let me know.

**Comment by erskordi** [comment]
Another thing I noticed is that this command:

```pip install --upgrade --no-deps --force-reinstall /nopt/nrel/apps/wheels/tensorflow-2.4.0-cp38-cp38-linux_x86_64.whl```

while it can give this error, it always works by changing `pip` to `pip3`, which is doable since all these examples use Python 3, right?

**Comment by KevinSayers** [comment]
Regarding `source` vs `conda` for activating the environment, `conda` was not the recommended way on Eagle because it could cause issues in some cases if users had altered their `.bashrc` with `conda init`. The newest version of Conda on Eagle should resolve this so we can just update to `conda activate ...` I think. 

In the conda env `pip` should be `pip3` anyways though isn't it?
